apiVersion: v2
name: pipem
description: Pipem Config
type: application
icon: "https://avatars.githubusercontent.com/u/96174842"

version: VERSION
appVersion: VERSION

dependencies:
  - name: "mongodb"
    version: "13.16.4"
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.install
  - name: "nats"
    repository: https://nats-io.github.io/k8s/helm/charts/
    version: "1.0.2"

maintainers:
  - name: Pipem.io
    email: info@pipem.io
    url: https://pipem.io
