log:
  level: "info"

api:
  domain: api.pipem.io
  schema: https://
  ingress:
    enabled: true
    class: kong
  cookie:
    secret: "pipem-io"
    domain: ".pipem.io"
    maxAge: "604800" # 7 days
    secure: "true"
    sameSite: "Strict"

app:
  domain: app.pipem.io
  ingress:
    enabled: true
    class: kong

username: "admin"
password: "pipem-io"

mongodb:
  install: false
  uri: ""
  auth:
    rootPassword: "f8MrA9Tp773StE582mw9"

configInit:
  image: docker.pipem.io/config-init
  tag: 0.4.0
