log:
  level: "info"

api:
  baseUrl: https://api.pipem.io
  domain: api.pipem.io
  ingress:
    enabled: true
    class: kong
  cookie:
    secret: "pipem-io"
    domain: ".pipem.io"
    maxAge: "604800" # 7 days
    secure: "true"
    sameSite: "Strict"

app:
  domain: app.pipem.io
  ingress:
    enabled: true
    class: kong

username: "pipem"
password: "pipem-io"

license: false

mongodb:
  install: false
  uri: ""
