apiVersion: v1
kind: Secret
metadata:
  name: pipem-secret
data:
  USERNAME: {{ .Values.username | b64enc }}
  PASSWORD: {{ .Values.password | b64enc }}
  COOKIE_SECRET: {{ .Values.api.cookie.secret | b64enc }}
  MONGODB_URI: {{ .Values.mongodb.uri | b64enc | quote }}
