apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipem-rb
  namespace: {{ .Release.Namespace  }}
  labels:
    app: pipem.io
subjects:
- kind: ServiceAccount
  name: pipem-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipem-role