apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipem-role
  namespace: {{ .Release.Namespace  }}
rules:
- apiGroups: [""]
  resources: ["secrets", "pods"]
  verbs: ["get", "list"]
